### ISSUE TITLE
(MAJOR) Error With Button Searching if Funds Have Been Sent - Stuck, But I Already Minted Successfully

### ISSUE THREAD

**Issue by liz-shinn** [threshold-network/token-dashboard#367]
(( PENDING - this may have been the intended interaction here ))

⛔️ If I refresh, re-connect my wallet, and come back to the Dapp, it gets hung on Step 2 and won't advance.

I have already minted successfully and the Tx History table shows that I have already minted.

<img width="570" alt="Screenshot 2023-01-26 at 5 51 39 PM" src="https://user-images.githubusercontent.com/57226633/214898810-e18f2d54-cd57-404f-b2d1-84850f75ae0e.png">

Even though the Tx History shows correctly that I have successfully minted:

<img width="338" alt="Screenshot 2023-01-26 at 5 56 43 PM" src="https://user-images.githubusercontent.com/57226633/214899165-8614eb28-b607-4f10-af24-d50d2faa1053.png">

**Comment by michalsmiarowski** [comment]
We decided to change how the flow works:

**1.** User generates deposit address, download JSON, disconnects at step 2 and reconnects again (did not reveal the deposit yet)

**Solution:** Show him step 2

**2.** User generates deposit address, download JSON, sends the funds to the deposit address and then disconnects at step 3 and reconnects again (did not reveal the deposit yet)

**Solution:** Show him step 3

**3.** User generates deposit address, download JSON, sends the funds to the deposit address and then reveal the deposit and sees the success modal (step 4). He then disconnects at step 4 and reconnects again

**Solution:** Show him step 1 because he already revealed the deposit

**Additional notes:**

Do not allow the user to reveal multiple deposits that were sent to the same deposit address. The dApp should only reveal the oldest un-revealed deposit transaction (sent to this deposit address) after clicking the minting button at step 3.

**The back button:**

**1.** Clicking the back button on step 2 will display the New Generation address modal and take user to step 1

**2.** Clicking the back button on step 3 will display the New Generation address modal and the user to step 1 (he already send funds at this point so no need to navigate him back to step 2)

**3.** Clicking Dismiss or back button at step 4 will navigate the user to the step 1 without displaying the New Generation address modal

**Comment by michalsmiarowski** [comment]
I will additionaly add here what @sashatanase proposed:

When the dApp recognizes that the funds were send to the deposit address in step 2 we will automatically navigate the user to step 3 without the need to click `I sent BTC` button.
