### ISSUE TITLE
tBTC Protocol History on Overview & Bridge Empty State in dApp

### ISSUE THREAD

**Issue by sashatanase** [threshold-network/token-dashboard#462]
How might we demonstrate to the user the latest activity across the bridge, to show that the tBTC protocol is a reliable & active solution that folks are using?

_Part 1 of 2 of a two-prong solution_
This issue covers the Overview/Bridge pages of the dapp. Part 2 is the website and is shown here: https://github.com/threshold-network/token-dashboard/issues/467

We need a tBTC TVL across the dApp  (all the tBTC tokens locked in the dApp from all the deposits and wallets) 

It should be on the dashboard Overview page. 

In this tBTC card we need to include

- dApp TVL
- user tBTC balance
- recent activity 
- system status for pending mints

**Comment by liz-shinn** [comment]
![Image](https://user-images.githubusercontent.com/57226633/221063122-9330c51d-f452-4699-bd50-d45c77aa6a66.jpg)

**Comment by liz-shinn** [comment]
In figma here: https://www.figma.com/file/Tx1lZc7us4SqCeAgbt1hBV/Threshold-Dapp?node-id=8149%3A228584&t=ouD0NQY2FTYopMmK-1

**Comment by liz-shinn** [comment]
![tBTC Overview - Wallet Portfolio Removed](https://user-images.githubusercontent.com/57226633/221724814-9f2e2315-1749-4c03-8ab5-ab70ef1ec58a.png)

On the Overview page, I've revised this based on a combination of the existing design & Sasha's design. The intent of my edits were to visually differentiate the two blocks of content by changing the table styles.

I used a list style that looks like entries or linear updates for the network mints. I called it "Latest Mints" but if we think "Historical Mints" works better can change. This will visually help these two blocks look like they show different things. I also left it outside of a grey box like the other TVL. On the lefthand side is all network information, and on the righthand side is all user information.

In this I did remove the Wallet Portfolio section in favor of a secondary feature banner. Everything on this Overview page was loud with all primary buttons, so I took down every action to a secondary CTA below the first two cards. 

This way we can focus the user at the top! 

My understanding is that token migration is no longer a product priority, so a link can suffice from the Overview, versus an entire card that has a lot of numbers and information in it. This will help to reduce the cognitive load of this screen, and was something that seemed like time to downgrade in importance.

Of course, if we feel that this is worth preserving, we can add it back, but I was attempting to curate this a bit and prioritize the view for the things we want them to do first.

**Comment by liz-shinn** [comment]
![Empty State](https://user-images.githubusercontent.com/57226633/221726995-0e7ba38b-cd57-4c5d-9cd2-511fb8e159db.png)

Revisions here! Since the goal was to "activate" the empty state page, I revised my earlier draft and got rid of including the minting activity on the Bridge page itself. This revision is based on Sasha's points that tBTC is quite complex and has a lot of info already, so we should not add too much more info if we can avoid it.

Instead, this page shows only when a wallet is not connected. It serves as an additional prompt & social proof that other folks have minted.

Instead of "Connect wallet to mint tBTC" -- I've instead written here "Ready to mint tBTC?". The intent being for the CTA of the button to answer that question, and the minting activity below it to also support this action.

This places the social proofing in direct context of minting.

**Comment by liz-shinn** [comment]
> the small listed cards are signifiers of buttons, so they should link towards Etherscan. If they're not active links, it might send mixed signals.

Yes, I think these should be buttons and link to Etherscan. We can have a light grey background hover action on these as well so there is an additional visual cue that they are buttons.

> this is the fact that the card looks as if it's disabled in the context of the layout. I don't know if this was your intention.

Nope, it was meant to look active. I think your edit of making this card a white background fixes this!

>  Though data or not, we've emphasised this for almost an entire year, so we should slowly get rid of the upgrade.

Agreed.
