### ISSUE TITLE
Bring "How it works" page to forefront

### ISSUE THREAD

**Issue by erdogan** [threshold-network/token-dashboard#547]
```[tasklist]
### Tasks
- [ ] https://github.com/threshold-network/token-dashboard/pull/630
```

**Comment by erdogan** [comment]
Let the users check the How it works page before the warning modal.

**Comment by sashatanase** [comment]
Proposed Solution

Show the modal only if the users hit Bridge in the secondary nav; otherwise, let them check the How it Works page and tBTC explorer.

Added How it works as a secondary button in the warning modal 

![image](https://github.com/threshold-network/token-dashboard/assets/40768736/df601a52-32d9-40e7-8ae1-49e190805d49)

Figma - https://www.figma.com/file/Tx1lZc7us4SqCeAgbt1hBV/Threshold-Dapp?type=design&node-id=9390%3A173582&mode=design&t=nnmPtmyh3yigcEoB-1
