### ISSUE TITLE
Leftover TACo improvements

### ISSUE THREAD

**Issue by theref** [threshold-network/token-dashboard#699]
A place to track minor TACo related improvements

**Comment by cygnusv** [comment]
<img width="264" alt="image" src="https://github.com/threshold-network/token-dashboard/assets/2564234/b41f4a8c-fc71-4b7d-b58d-91e528e00e7c">

Context: staker successfully authorized with TACo, including bonded operator, but not authorized for tBTC/RB. 

When visiting the staking page, this pop up is shown for bonding operators. This doesn't make sense for this staker, since (1) they're already bonded with a TACo operator, and (2) they're not authorized with tBTC/RB yet (so they can't bond an operator)

**Comment by derekpierre** [comment]
Not a blocker, but better error handling of error cases for bonding would be good.

Got the following non-descript dialog when I attempted to bond and operator address (using Sepolia)
![Screenshot 2023-12-13 at 10 09 46 AM](https://github.com/threshold-network/token-dashboard/assets/19150641/ecce9c6e-50b6-48a1-bd1f-44943b71a928)

The failure is correct because that operator address is already a staking provider address on Sepolia. I can see the error in the javascript console:
```
"execution reverted: Specified operator is a provider"
```

but it would be nice to show the error message. This is probably not TACo-specific, but symptomatic of a broader issue in the dashboard. In any case, just something of note.

**Comment by cygnusv** [comment]
> Got the following non-descript dialog when I attempted to bond and operator address (using Sepolia)

I also got the same dialog, when trying to bond to the same operator (which would fail with TACoApplication, as expected)

**Comment by derekpierre** [comment]
After successfully bonding an operator on Sepolia, the success dialog has the operator address but is missing the provider address.
![Screenshot 2023-12-13 at 10 33 41 AM](https://github.com/threshold-network/token-dashboard/assets/19150641/e851a603-bc58-41c0-845d-5eb83bc18ae8)

**Comment by arjunhassard** [comment]
**Edits to Bonus Modal**
<img width="494" alt="image" src="https://github.com/threshold-network/token-dashboard/assets/2332199/ed70dfdc-78ff-4662-bda8-2b250b4f6bcc">

(1) Title -> **TACo Token Lock-up Extension**

(2) Top text -> 
You can lock up tokens (authorized to TACo) for longer durations in order to receive a yield bonus of corresponding size. **Once you click Commit below, you cannot go back and edit this lock-up duration.**
Please read the [bonus rules](https://docs.threshold.network/staking-and-running-a-node/taco-node-setup/taco-authorization-and-operator-registration/one-off-commitment-bonus) before deciding. 

(3) Change 'voluntary' to 'extension' in each of the options. 

(4) Bottom text ->
Once you choose a lock-up duration and hit Commit below, your tokens will be irreversibly locked until the unlock date at the earliest. This cannot be undone. You may authorize more tokens to the same unlock horizon before the bonus deadline (January 15th 2024), but you cannot decrease the amount. You must also manually initiate deauthorization 6 months before the unlock date stated if you wish to withdraw tokens on said date. For more rules and information, head to  the [documentation](https://docs.threshold.network/staking-and-running-a-node/taco-node-setup/taco-authorization-and-operator-registration/one-off-commitment-bonus). 

(5) Can we add the date calculator, so the staker knows the earliest date they could theoretically unlock their tokens? 

(6) Can we also display the amount of T currently authorized to TACo, so they don't have to go back and check? It's a helpful sanity check.

**Comment by theref** [comment]
Fixed by #625
